parameters:

services:

    app.user_encode_password_subscriber:
        class: AppBundle\EventListener\User\EncodePasswordSubscriber
        arguments: [ "@security.password_encoder" ]
        tags:
            - { name: doctrine.event_subscriber }

    app.canonicalizer_email_subscriber:
        class: AppBundle\EventListener\User\CanonicalizerEmailSubscriber
        arguments: [ "@app.helper.canonicalizer" ]
        tags:
            - { name: doctrine.event_subscriber }