parameters:

services:

    app.user_encode_password_subscriber:
        class: AppBundle\EventListener\User\EncodePasswordSubscriber
        arguments: [ "@security.password_encoder" ]
        tags:
            - { name: doctrine.event_subscriber }