parameters:

services:

    app.user_encode_password_subscriber:
        class: AppBundle\EventListener\User\EncodePasswordSubscriber
        arguments: [ "@security.password_encoder" ]
        tags:
            - { name: doctrine.event_subscriber }

    app.canonicalizer_email_subscriber:
        class: AppBundle\EventListener\User\CanonicalizerEmailSubscriber
        arguments: [ "@app.helper.canonicalizer" ]
        tags:
            - { name: doctrine.event_subscriber }

    app.timestampable_subscriber:
        class: AppBundle\EventListener\TimestampableSubscriber
        arguments: ["@annotations.reader"]
        tags:
            - { name: doctrine.event_subscriber }

    app.resetting_request_send_email_subscriber:
        class: AppBundle\EventListener\Security\ResettingRequestSendEmailSubscriber
        arguments:
            - "@swiftmailer.mailer"
            - "@translator.default"
            - "@templating.engine.twig"
            - "@router"
            - "@session.flash_bag"
            - "@parameter_bag"
        tags:
            - { name: kernel.event_subscriber }