imports:

    # Security #
    - { resource: security/services.yml }

    # Repository #
    - { resource: repository/services.yml }

    # Manager #
    - { resource: manager/services.yml }

    # Form #
    - { resource: form/services.yml }

    # Listener #
    - { resource: listener/services.yml }