#default:
#    resource: "@AppBundle/Controller/Web/Default/"
#    type:     annotation

admin:
    resource: "@AppBundle/Controller/Web/Admin/"
    type:     annotation
    prefix: /admin

portal:
    resource: "@AppBundle/Controller/Web/Portal/"
    type:     annotation
    prefix: /portal
