parameters:

services:

    app.portal_authenticator:
        class: AppBundle\Security\PortalFormAuthenticator
        arguments: ['@app.portal_profile_manager', '@security.password_encoder', '@router']

    app.portal_last_login_subscriber:
        class: AppBundle\EventListener\Security\LastLoginSubscriber
        arguments: ['@app.portal_profile_manager']
        tags:
            - { name: kernel.event_subscriber }