services:

    app.admin_resetting_request_form_handler:
        class: AppBundle\Form\Security\Handler\ResettingRequestFormHandler
        arguments: [ "@app.admin_profile_manager", "@app.helper.token_generator", "@translator.default", "%admin_security.resetting.token_ttl%" ]

    app.admin_resetting_reset_form_handler:
        class: AppBundle\Form\Security\Handler\ResettingResetFormHandler
        autowire: true

    app.admin_change_password_form_handler:
        class: AppBundle\Form\Security\Handler\ChangePasswordFormHandler
        arguments: [ "@app.admin_profile_manager", "@session.flash_bag", "@translator.default" ]

    app.admin_profile_form_handler:
        class: AppBundle\Form\Admin\Handler\AdminProfileFormHandler
        arguments: [ "@app.admin_profile_manager" ]