services:

    app.admin_resetting_request_form_handler:
        class: AppBundle\Form\Security\Handler\ResettingRequestFormHandler
        arguments: [ "@app.admin_profile_manager", "@app.helper.token_generator", "@translator.default", "@=service('app.helper.parameters').getParams('admin')" ]

    app.admin_resetting_reset_form_handler:
        class: AppBundle\Form\Security\Handler\ResettingResetFormHandler
        arguments: ['@app.admin_profile_manager', '@app.helper.flash_bag']

    app.admin_change_password_form_handler:
        class: AppBundle\Form\Security\Handler\ChangePasswordFormHandler
        arguments: [ "@app.admin_profile_manager", "@app.helper.flash_bag" ]

    app.admin_profile_form_handler:
        class: AppBundle\Form\Admin\Handler\AdminProfileFormHandler
        arguments: [ "@app.admin_profile_manager" ]