parameters:

services:

    app.admin_authenticator:
        class: AppBundle\Security\AdminFormAuthenticator
        autowire: true

    app.admin_last_login_subscriber:
        class: AppBundle\EventListener\User\LastLoginSubscriber
        arguments: [ "@app.admin_user_manager" ]
        tags:
            - { name: kernel.event_subscriber }