parameters:

services:

    app.admin_authenticator:
        class: AppBundle\Security\AdminFormAuthenticator
        arguments: ['@app.admin_profile_manager', '@security.password_encoder', '@router']

    app.admin_last_login_subscriber:
        class: AppBundle\EventListener\Security\LastLoginSubscriber
        arguments: ['@app.admin_profile_manager']
        tags:
            - { name: kernel.event_subscriber }

