parameters:

services:

    app.helper.canonicalizer:
        class: AppBundle\Helper\CanonicalizerHelper

    app.helper.token_generator:
        class: AppBundle\Helper\TokenGeneratorHelper
        autowire: true

    app.helper.flash_bag:
        class: AppBundle\Helper\FlashBagHelper
        autowire: true

    app.helper.pagination:
        class: AppBundle\Helper\PaginationHelper
        autowire: true
        #arguments: ['@request', '@doctrine.orm.entity_manager']